project: "eggs"
version: "0.2"
updated: "2023-01-31T00:00:00.000Z"
debug: true
options:
 menuEntry:
 - name: "adapt"
   descr: "adapt monitor resolution for VM only"
   command: "eggs adapt"
   flags: 
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"
   dependencies: 
   - dep: "ls /usr/bin/adapt"


 - name: "calamares"
   descr: "calamares configuration or install and configure it"
   command: "sudo eggs calamares"
   dependencies: 
   - dep: "ls /etc/calamares"
   flags:
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "install"
     descr: "install calamares and it's dependencies"
     type: "boolean"
   - flag: "release"
     descr: "release: remove calamares and all it's dependencies after the installation"
     type: "boolean"
   - flag: "remove"
     descr: "remove calamares and it's dependencies"
     type: "boolean"
   - flag: "theme"
     descr: "theme/branding for eggs and calamares"
     type: "string"
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"


 - name: "dad"
   descr: "ask help from daddy - configuration helper"
   command: "sudo eggs dad"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
    - flag: "clean"
      descr: "clean and rebuild configuration"
      type: "boolean"
    - flag: "default"
      descr: "clean and rebuild configuration default values"
      type: "boolean"


 - name: "help"
   descr: "display help"
   command: "eggs -h"
   dependencies: 
   - dep: "ls /usr/bin/eggs"


 - name : "kill"
   descr: "kill the eggs/free the nest"
   command: "sudo eggs kill"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"


 - name: "install"
   descr: "krill TUI system installer - the egg becomes a chick"
   command : "sudo eggs install"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
    - flag: "none"
      descr: " Swap none: 256M"
      type: "boolean"
    - flag: "suspend"
      descr: "Swap suspend: RAM x 2"
      type: "boolean"
    - flag: "custom"
      descr: "custom unattended configuration"
      type: "string"
    - flag: "domain"
      descr: "Domain name, defult: .local"
      type: "string"
    - flag: "help"
      descr: "help"
      type: "boolean"
    - flag: "ip"
      descr: "hostname as ip, eg: ip-192-168-1-33"
      type: "boolean"
    - flag: "crypted"
      descr: "Crypted CLI installation"
    - flag: "Crypted CLI installation"
      descr: "assume Yes"
      type: "boolean"
    - flag: "pve"
      descr: "Proxmox VE partition"
      type: "boolean"
    - flag: "random"
      descr: "Add random chars to hostname, eg: colibri-ay412dt"
      type: "boolean"
    - flag: "small"
      descr: "Swap small: RAM"
      type: "boolean"
    - flag: "unattende"
      descr: "Unattended installation"
      type: "boolen"
    - flag: "verbose"
      descr: "verbose"
      type: "boolean"


 - name: "produce"
   descr: "the system produces an egg: iso image of your system"
   command : "sudo eggs produce"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "addons"
     descr: "addons to be used: adapt, ichoice, pve, rsupport"
     type: "string[]"
   - flag: "backup"
     descr: "backup mode (CRYPTED)"
     type: "boolean"
   - flag: "basename"
     descr: "basename, default hostname"
     type: "string"
   - flag: "clone"
     descr: "clone mode"
     type: "boolean"
   - flag: "fasr"
     descr: "fast compression"
     type: "boolean"
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "max"
     descr: "max compression"
     type: "boolean"
   - flag: "nointeractive"
     descr: "assume Yes"
     type: "boolean"
   - flag: "prefix"
     descr: "prefix=value"
     type: "string"
   - flag: "release"
     descr: "release: max compression, remove penguins-eggs and calamares after installation"
     type: "boolean"
   - flag: "script"
     descr: "script mode. Just generate scripts to manage iso build"
     type: "boolean"
   - flag: "theme"
     descr: "theme for livecd, calamares branding and partitions"
     type: "string"
   - flag: "verbose"
     descr: "verbos"
     type: "boolean"
   - flag: "yolk"
     descr: "force yolk renew"
     type: "boolean"

 - name: "syncfrom"
   descr: "restore users and user data from a LUKS volumes"
   command: "sudo eggs syncfrom"
   dependencies:
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "file"
     descr: "file LUKS volume encrypted"
     type: "string"
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "rootdir"
     descr: "rootdir of the installed system, when used from live"
     type: "string"
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"
   - flag: "delete"
     descr: "delete extraneous files from dest dirs"
     type: "string"

 - name: "syncto"
   descr: "save users and user data in a LUKS volume inside the iso"
   command: "sudo eggs syncto"
   dependencies:
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "file"
     descr: "file LUKS volume encrypted"
     type: "string"
   - flag: "help"
     descr: "help"
     type: "boolean"
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"
   - flag: "delete"
     descr: "delete extraneous files from dest dirs"
     type: "string"

 - name: "status"
   descr: "eggs status"
   command: "eggs status"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "verbose"
     descr: "verbose"
     type: "boolean"
   - flag: "help"
     descr: "help"
     type: "boolean"


 - name: "update"
   descr: "update the penguin's eggs tool"
   command: "sudo eggs update"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   flags:
   - flag: "verbose"
     descr: "verbos"
     type: "boolean"
   - flag: "help"
     descr: "help"
     type: "boolean"


 - name: "export"
   descr: "export packages/iso"
   command: "eggs export "
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   submenu:
     - name: "deb"
       descr: "export deb packages to the destination host"
       command: "eggs export deb"
       flags:
       - flag: "all"
         descr: "export all archs"
         type: "boolean"
       - flag: "clean"
         descr: "remove old .deb before to copy"
         type: "boolean"
       - flag: "help"
         descr: "help"
         type: "boolean"
       - flag: "verbose"
         descr: "verbose"
         type: "boolean"

     - name: "iso"
       descr: "export isos in the destination host"
       command: "eggs export iso"
       flags:
       - flag: "backup"
         descr: "export backup iso"
         type: "boolean"
       - flag: "clean"
         descr: "delete old ISOs before to copy"
         type: "boolean"
       - flag: "help"
         descr: "help"
         type: "boolean"


 - name: "tools"
   descr: "various tools"
   command: "sudo eggs tools"
   dependencies: 
   - dep: "ls /usr/bin/eggs"
   submenu:
   - name: "clean"
     descr: "clean system log, apt, etc"
     command: "sudo eggs tools clean"
     flags:
      - flag: "help"
        descr: "help"
        type: "boolean"
      - flag: "verbose"
        descr: "verbose"
        type: "boolean"

   - name: "ppa"
     descr: "add/remove penguins-eggs-ppa repository"
     command: "sudo eggs tools ppa"
     flags:
      - flag: "add"
        descr: "add penguins-eggs-ppa repository"
        type: "boolean"
      - flag: "help"
        descr: "help"
        type: "boolean"
      - flag: "remove"
        descr: "remove penguins-eggs-ppa repository"
        type: "boolean"

   - name: "skel"
     descr: "update skel from home configuration"
     command: "sudo eggs tools skel"
     flags:
      - flag: "help"
        descr: "help"
        type: "boolean"
      - flag: "user"
        descr: "user to be used"
        type: "string"
      - flag: "verbose"
        descr: "verbose"
        type: "boolean"

   - name: "yolk"
     descr: "configure eggs to install without internet"
     command: "sudo eggs tools yolk"
     flags:
      - flag: "help"
        descr: "help"
        type: "boolean"
      - flag: "verbose"
        descr: "verbose"
        type: "boolean"
        
 - name: "quit"
   descr: "exit"
   command: "exit 0"
