project: eggs
version: 9.3.23
updated: "2023-02-19T00:00:00.000Z"
debug: true
options:
  menuEntry:
  - name: adapt
    descr: adapt monitor resolution for VM only
    command: eggs adapt
    dependencies:
      - dep: ls /usr/bin/adapt
  #- name: analyze
  #  descr: analyze for syncto
  #  command: eggs analyze
  - name: calamares
    descr: configure calamares or install or configure it
    command: eggs calamares --help
  #- name: config
  #  descr: Configure and install prerequisites deb packages to run it
  #  command: sudo eggs config
  - name: cuckoo
    descr: PXE start with proxy-dhcp
    command: sudo eggs cuckoo
  - name: dad
    descr: ask help from daddy - TUI configuration helper
    command: sudo eggs dad --default
  - name: install
    descr: 'krill: the CLI system installer - the egg became a penguin!'
    command: sudo eggs install
    dependencies:
    - dep: ls /run/live/rootfs/filesystem.squashfs/
  - name: kill
    descr: kill the eggs/free the nest
    command: sudo eggs kill
    dependencies:
    - dep: ls /home/eggs
  - name: produce
    descr: produce a live image from your system whithout your data
    command: eggs produce --help
  - name: status
    descr: informations about eggs status
    command: eggs status
  #- name: syncfrom
  #  descr: restore users and user data from a LUKS volumes
  #- name: syncfto
  #  descr: saves users and user data in a LUKS volume inside the iso
  #  command: eggs syncto --help
  #- name: update
  #  descr: update the penguin's eggs tool
  #  command: eggs update --help
  - name: DOCUMENTATION
    descr: ""
    command: ""
    menuEntry:
    - name: book
      desc: book
      command: xdg-open https://penguins--eggs-net.translate.goog/book/italiano9.3?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en
    - name: man 
      desc: man pages
      command: man eggs
    - name: "man pages html"
      desc: man pages html
      command: xdg-open file:///usr/lib/penguins-eggs/manpages/doc/man/eggs.html
    - name: repository
      desc: repository
      command: xdg-open https://github.com/pieroproietti/penguins-eggs
    - name: "sourceforge page"
      desc: sourceforge page
      command: xdg-open https://sourceforge.net/projects/penguins-eggs/
  - name: EXPORT
    menuEntry: 
    - name: deb
      descr: 
      command: eggs export deb
      dependencies:
      - dep: ls ${HOME}/penguins-eggs/perrisbrewery/working
    - name: iso
      descr: export iso in the destination host
      command: eggs export iso
      dependencies:
      - dep: ls /home/eggs/*.iso
    - name: quit
      descr: quit
      command: exit 0
  - name: TOOLS
    descr: ""
    command: ""
    menuEntry: 
    - name: ppa
      descr: add/remove PPA repositories (Debian family)
      command: eggs tools ppa --help
    - name: skel
      descr: update skel from home configuration
      command: eggs tools skel --help
    - name: stat
      descr: get statistics from sourceforge
      command: eggs tools stat
    - name: yolk
      descr: configure eggs to install without internet
      command: sudo eggs tools yolk
  - name: WARDROBE
    descr: ""
    command: ""
    menuEntry: 
    - name: get
      descr: get wardrobe
      command: eggs wardrobe get
    - name: list
      descr: list costumes and accessoires in wardrobe
      command: eggs wardrobe list
      dependencies:
        - dep: ls ${HOME}/.wardrobe
    - name: show
      descr: show costumes/accessories in wardrobe
      command: eggs wardrobe show
      dependencies:
        - dep: ls ${HOME}/.wardrobe
    - name: wear
      descr: wear costume/accessories from wardrobe
      command: eggs wardrobe wear --help
      dependencies:
        - dep: ls ${HOME}/.wardrobe
    - name: quit
      command: exit 0
  - name: QUIT
    command: exit 0
